name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "requirements*.txt"
  push:
    branches: [ main ]
  workflow_dispatch: {}  # чтобы можно было запустить вручную из вкладки Actions

jobs:
  test:
    name: Pytests (Ubuntu, Py3.10–3.12)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    permissions:
      contents: read     # минимально необходимые права

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install ".[dev]" || true; fi

      - name: Static checks (ruff/mypy)  # опционально
        run: |
          pip install ruff mypy || true
          ruff check . || true
          mypy . || true

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --junitxml=pytest.xml --cov=. --cov-report=xml || pytest -q
        continue-on-error: false

      - name: Upload test report (artifact)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.python-version }}
          path: |
            pytest.xml
            coverage.xml
